In [1]:
import pandas as pd

In [2]:
raw_rating_data = pd.read_csv("./data/ratings.csv")

In [3]:
raw_rating_data.tail()

          userId  movieId  rating   timestamp
25000090  162541    50872     4.5  1240953372
25000091  162541    55768     2.5  1240951998
25000092  162541    56176     2.0  1240950697
25000093  162541    58559     4.0  1240953434
25000094  162541    63876     5.0  1240952515

In [4]:
sorted_rating = raw_rating_data.sort_values(by=['timestamp'], axis=0)

In [5]:
sorted_rating.tail()

          userId  movieId  rating   timestamp
13207880   85523   168252     4.0  1574327479
1284508     8642   202101     2.0  1574327512
13207893   85523   204704     4.0  1574327533
1284464     8642   122914     4.0  1574327549
13207877   85523   149406     4.5  1574327703

In [6]:
rating_data_newest = sorted_rating[-100000:-1]

In [7]:
rating_data_newest.head()

         userId  movieId  rating   timestamp
8848755   57688   128360     4.5  1571550775
8848774   57688   152077     3.5  1571550780
8848711   57688   106920     4.0  1571550815
8848331   57688      111     4.0  1571550819
8848821   57688   185029     4.0  1571550822

In [8]:
def rating_filter(input_data, threshold = 100):
    data = input_data.copy()
    #threshold개 이상 평가를 남긴 row만 남김
    x = data['userId'].value_counts()>=threshold
    y = set(x[x].index)
    data = data[data['userId'].isin(y)]
    
    return data.reset_index(drop=True)

In [9]:
rating_data_newest_cert = rating_filter(rating_data_newest, 100)

In [10]:
rating_data_newest_cert.to_csv("./data/rating_cert.csv")

In [11]:
raw_pivot = rating_data_newest_cert.pivot(index = 'userId', columns='movieId', values='rating')

In [12]:
movie_count = raw_pivot.count(axis = 0)

In [13]:
movies_to_erase = []
for c in raw_pivot.columns.to_list():
    if movie_count[c]<20 : 
        movies_to_erase.append(c)

In [14]:
raw_pivot_temp = raw_pivot.drop(movies_to_erase, axis=1)

In [15]:
moviesList = raw_pivot_temp.columns.to_list()

In [16]:
movie_raw = pd.read_csv("./data/movies.csv")

In [17]:
movie_raw.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [18]:
movie_cert = movie_raw[movie_raw["movieId"].isin(moviesList)]

In [19]:
movie_cert

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
5,6,Heat (1995),Action|Crime|Thriller
9,10,GoldenEye (1995),Action|Adventure|Thriller
15,16,Casino (1995),Crime|Drama
18,19,Ace Ventura: When Nature Calls (1995),Comedy
31,32,Twelve Monkeys (a.k.a. 12 Monkeys) (1995),Mystery|Sci-Fi|Thriller
33,34,Babe (1995),Children|Drama
38,39,Clueless (1995),Comedy|Romance
46,47,Seven (a.k.a. Se7en) (1995),Mystery|Thriller
49,50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller
69,70,From Dusk Till Dawn (1996),Action|Comedy|Horror|Thriller
102,104,Happy Gilmore (1996),Comedy
108,110,Braveheart (1995),Action|Drama|War
109,111,Taxi Driver (1976),Crime|Drama|Thriller
148,150,Apollo 13 (1995),Adventure|Drama|IMAX
151,153,Batman Forever (1995),Action|Adventure|Comedy|Crime
163,165,Die Hard: With a Vengeance (1995),Action|Crime|Thriller
206,208,Waterworld (1995),Action|Adventure|Sci-Fi
214,216,Billy Madison (1995),Comedy
220,223,Clerks (1994),Comedy
228,231,Dumb & Dumber (Dumb and Dumber) (1994),Adventure|Comedy
250,253,Interview with the Vampire: The Vampire Chroni...,Drama|Horror
257,260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Sci-Fi
285,288,Natural Born Killers (1994),Action|Crime|Thriller
289,293,Léon: The Professional (a.k.a. The Professiona...,Action|Crime|Drama|Thriller
292,296,Pulp Fiction (1994),Comedy|Crime|Drama|Thriller
312,316,Stargate (1994),Action|Adventure|Sci-Fi
314,318,"Shawshank Redemption, The (1994)",Crime|Drama
339,344,Ace Ventura: Pet Detective (1994),Comedy
...,...,...,...
51785,183897,Isle of Dogs (2018),Animation|Comedy
52320,185029,A Quiet Place (2018),Drama|Horror|Thriller
53497,187541,Incredibles 2 (2018),Action|Adventure|Animation|Children
53523,187593,Deadpool 2 (2018),Action|Comedy|Sci-Fi
53524,187595,Solo: A Star Wars Story (2018),Action|Adventure|Children|Sci-Fi
53867,188301,Ant-Man and the Wasp (2018),Action|Adventure|Comedy|Fantasy|Sci-Fi
54276,189203,Upgrade (2018),Action|Comedy|Horror|Sci-Fi|Thriller
54332,189333,Mission: Impossible - Fallout (2018),Action|Adventure|Thriller
54496,189713,BlacKkKlansman (2018),Comedy|Crime|Drama
55641,192385,A Star Is Born (2018),Drama|Romance
55643,192389,Venom (2018),Action|Horror|Sci-Fi|Thriller
55821,192803,Bohemian Rhapsody (2018),Drama
56336,193944,The Ballad of Buster Scruggs (2018),Comedy|Drama|Western
56368,194016,Ralph Breaks the Internet (2018),Animation|Children
56570,194448,Green Book (2018),Comedy|Drama
56890,195159,Spider-Man: Into the Spider-Verse (2018),Action|Adventure|Animation|Sci-Fi
57462,196417,How to Train Your Dragon: The Hidden World (2019),Adventure|Animation|Children
57668,196889,Glass (2019),Drama|Horror|Mystery|Sci-Fi|Thriller
57716,196997,Black Mirror: Bandersnatch (2018),Drama|Mystery|Sci-Fi|Thriller
57794,197175,Alita: Battle Angel (2019),Action|Romance|Sci-Fi|Thriller
58023,197711,Us (2019),Horror|Thriller
59419,200818,John Wick: Chapter 3 – Parabellum (2019),Action|Crime|Thriller
59429,200838,Pokémon: Detective Pikachu (2019),Action|Children|Crime|Fantasy|Mystery
59767,201588,Toy Story 4 (2019),Adventure|Animation|Children|Comedy
59794,201646,Midsommar (2019),Drama|Horror|Mystery
59844,201773,Spider-Man: Far from Home (2019),Action|Adventure|Sci-Fi
60090,202429,Once Upon a Time in Hollywood (2019),Comedy|Drama
60095,202439,Parasite (2019),Comedy|Drama
61005,204698,Joker (2019),Crime|Drama|Thriller
61253,205383,El Camino: A Breaking Bad Movie (2019),Crime|Drama|Thriller

In [20]:
movie_cert.to_csv("./data/movie_cert.csv", index=False)

In [21]:
movie_cert.head()

    movieId             title                                       genres
0         1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
1         2    Jumanji (1995)                   Adventure|Children|Fantasy
5         6       Heat (1995)                        Action|Crime|Thriller
9        10  GoldenEye (1995)                    Action|Adventure|Thriller
15       16     Casino (1995)                                  Crime|Drama

In [22]:
raw_pivot

movieId,1,2,3,4,5,6,7,8,9,10,...,208737,208745,208765,208800,208837,208863,208869,209063,209073,209153
userId,,,,,,,,,,,,,,,,,,,,,
4,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1543,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1746,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2111,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2653,NaN,0.5,NaN,NaN,NaN,2.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6915,4.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8461,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9881,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10789,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10930,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12851,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15073,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15594,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16341,4.0,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17105,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17495,NaN,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17875,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18786,4.0,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19024,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19719,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19997,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20091,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21286,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21810,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24266,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141832,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
143437,3.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145672,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147040,NaN,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.5
147566,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147709,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148309,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149626,NaN,NaN,4.0,NaN,4.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149761,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149980,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
150655,4.0,4.0,NaN,NaN,NaN,4.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153802,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154545,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155991,3.5,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156357,NaN,NaN,4.0,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
156778,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
157358,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.5,NaN,NaN,NaN,NaN,NaN,NaN
157607,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158539,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159005,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159185,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159474,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160445,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
161485,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
162190,NaN,NaN,NaN,NaN,NaN,3.5,NaN,NaN,NaN,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN